name: build
on:
  - push
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: "2015"
        run: cargo run --release
        working-directory: "2015/"
      - name: "2021"
        run: cargo run --release
        working-directory: "2021/"
